```{r}
#| include: FALSE
source("header.R")
```

## Preface {.unnumbered}

In this textbook we cover the contents of an introductory statistics class, as typically taught to undergraduate psychology, health or social science students. The book covers how to get started in jamovi as well as giving an introduction to data manipulation. From a statistical perspective, the book discusses descriptive statistics and graphing first, followed by chapters on probability theory, sampling and estimation, and null hypothesis testing. After introducing the theory, the book covers the analysis of contingency tables, correlation, t-tests, regression, ANOVA and factor analysis. Bayesian statistics are touched on at the end of the book. 

This book is an adaptation of DJ Navarro (2018). Learning statistics with R: A tutorial for psychology students and other beginners. (Version 0.6). [https://learningstatisticswithr.com/](https://learningstatisticswithr.com/).

The jamovi version of this book was first released in 2018, as version 0.65. Versions 0.70 and 0.75 were released in subsequent years with corrections and additions; details of the changes in earlier versions of the book can be found in the preface to version 0.75: [https://github.com/user-attachments/files/18124061/learning-statistics-with-jamovi-0.75.pdf](https://github.com/user-attachments/files/18124061/learning-statistics-with-jamovi-0.75.pdf). In that time, many people have contacted us asking for a hard copy version of the book. To achieve this, and to preserve the open source attributes of the book and materials, we have worked with Open Book Publishers in Cambridge, UK, to release this updated version. Open Book Publishers are the leading independent open access publisher of academic research in the Humanities and Social Sciences in the UK. They are award-winning, not-for-profit, run by scholars, and committed to making high-quality research freely available to readers around the world. 

:::{.callout-note}
A pdf version of the book is available for free download from Open Book Publishers ([https://www.openbookpublishers.com/books/10.11647/obp.0333](https://www.openbookpublishers.com/books/10.11647/obp.0333)). All the data files you need can be accessed for free within jamovi via an add-on module in the jamovi library. Or you can download the files from [https://www.learnstatswithjamovi.com](https://www.learnstatswithjamovi.com). 
:::

If you spot any mistakes, or have any suggestions, please do let us know by raising an issue at [https://github.com/davidfoxcroft/lsj-book/issues](https://github.com/davidfoxcroft/lsj-book/issues).

*David Foxcroft  
January 1st, 2025*


:::{.content-visible when-format="html"}
**Citation**: Danielle J. Navarro and David R. Foxcroft, *Learning Statistics with jamovi: A Tutorial for Beginners in Statistical Analysis*. Cambridge, UK: Open Book Publishers, 2025, https://doi.org/10.11647/OBP.0333
:::
